Repository Uttug-Seuja/luck-lottery-server, pull requests merged in 2024-02, with the labels that each got.

#55 docs : Git Actions를 사용하여 CD 구축
  .github/workflows/cd.yml
  Dockerfile
  src/main/resources/application.yml
Labels: docs, backend

#59 fix : ci.yml, cd.yml 변경
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: fix, backend

#60 feat : crawling pension lottery
  build.gradle
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/domain/WinningPensionLottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/domain/repository/WinningPensionLotteryJdbcRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/domain/repository/WinningPensionLotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/dto/request/LotteryDrawDayDto.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/dto/request/WinningPensionLotteryCrawlingDto.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/exception/CrawlingIOException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/exception/DataNotFoundException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/exception/PageAccessException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/exception/WinningPensionLotteryNotFoundException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/presentation/WinningPensionLotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/service/WinningPensionLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/ScheduledConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/LuckLotteryIoException.java
  src/main/java/uttugseuja/lucklotteryserver/global/scheduler/WinningPensionLotteryUpdateScheduling.java
Labels: feat, backend

#63 fix : cd.yml docker pull 명령어 변경
  .github/workflows/cd.yml
Labels: fix, backend

#65 fix : cd.yml 호스트 포트 변경
  .github/workflows/cd.yml
Labels: fix, backend

#66 feat : random pension lottery
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/PensionLottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/repository/PensionLotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/exception/OverRoundException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/PensionLotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/dto/request/CreatePensionLotteryRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/dto/response/RandomPensionLotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/service/PensionLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
Labels: feat, backend

#68 fix : random pension lottery round
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/PensionLottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/repository/PensionLotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/vo/PensionLotteryBaseInfoVo.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/service/PensionLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/global/scheduler/WinningPensionLotteryUpdateScheduling.java
Labels: fix, backend

#71 feat : swagger 추가
  build.gradle
  src/main/java/uttugseuja/lucklotteryserver/global/config/SecurityConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: feat, backend

#75 feat : 로그인 스웨거 적용
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/CredentialController.java
Labels: feat, backend

#76 feat : winning lottery 저장
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/domain/WinningLottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/domain/repository/WinningLotteryJdbcRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/domain/repository/WinningLotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/domain/vo/WinningLotteryBaseInfoVo.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/presentation/WinningLotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/service/WinningLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/global/time/TimeTrace.java
  src/main/java/uttugseuja/lucklotteryserver/global/time/TimeTraceAspect.java
  src/main/resources/application.yml
Labels: feat, backend

#78 fix : docker 오류 잡기
  .github/workflows/cd.yml
Labels: fix, backend

#80 fix : docker 오류 해결
  .github/workflows/cd.yml
Labels: fix, backend

#81 feat : 연금 복권 당첨 조회기능
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/domain/WinningPensionLottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/domain/repository/WinningPensionLotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/domain/vo/WinningPensionLotteryBaseInfoVo.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/dto/response/WinningPensionLotteryBonusNumbersResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/dto/response/WinningPensionLotteryNumbersResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/service/WinningPensionLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/PensionLottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/repository/PensionLotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/vo/PensionLotteryBaseInfoVo.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/PensionLotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/dto/response/PensionLotteryNumbersResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/dto/response/PensionLotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/service/PensionLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/global/common/Rank.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/SecurityConfig.java
Labels: feat, backend

#83 fix : getRSAPublicKey 로직 수정
  src/main/java/uttugseuja/lucklotteryserver/global/security/JwtOIDCProvider.java
Labels: fix, backend

#84 feat : 최근 회차의 당첨 로또 정보 조회하기
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/domain/repository/WinningLotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/exception/WinningLotteryNotFoundException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/presentation/WinningLotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/presentation/dto/response/WinningLotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/service/WinningLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
Labels: feat, backend

#86 fix : lottery 저장 로직 변경
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/LotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/request/CreateLotteryRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/service/WinningLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/service/WinningLotteryUtils.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/GlobalExceptionHandler.java
Labels: feat, fix, backend

#88 feat : 당첨 로또 매주 토요일 9시에 최신화
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/service/WinningLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/service/WinningLotteryUtils.java
  src/main/java/uttugseuja/lucklotteryserver/global/scheduler/WinningLotteryScheduled.java
Labels: feat, backend

#90 docs : log 추가
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/CredentialService.java
Labels: docs, backend

#93 feat : recent_winning_lottery_info
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/dto/response/WinningPensionLotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/presentation/WinningPensionLotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/service/WinningPensionLotteryService.java
Labels: feat, backend

#96 fix : yml 변경
  .github/workflows/cd.yml
  src/main/resources/application.yml
Labels: fix, backend

#97 fix : cd.yml 다시 변경
  .github/workflows/cd.yml
Labels: feat, fix, backend

#99 fix : 사용자 연금복권 목록 조회 로직 변경
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/service/WinningPensionLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/service/WinningPensionLotteryUtils.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/repository/PensionLotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/dto/request/CreatePensionLotteryRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/dto/response/PensionLotteryNumbersResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/dto/response/PensionLotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/service/PensionLotteryService.java
Labels: fix, backend

#102 feat : profile image upload
  build.gradle
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/domain/ProfileImage.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/domain/repository/ProfileImageRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/exception/ProfileImageNotFoundException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/presentation/AssetController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/presentation/dto/response/ProfileImageDto.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/service/AssetService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/service/AssetUtils.java
  src/main/java/uttugseuja/lucklotteryserver/domain/image/exception/BadFileExtensionException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/image/exception/BadProfilePathException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/image/exception/FileEmptyException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/image/exception/FileOversizeException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/image/exception/FileUploadFailException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/image/presentation/ImageController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/image/presentation/dto/UploadImageResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/image/service/ImageService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/image/service/ImageUtils.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/User.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/vo/UserInfoVO.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/presentation/UserController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/presentation/dto/request/ChangeProfileRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/presentation/dto/response/UserProfileResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/service/UserService.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/S3Config.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: feat, backend

#104 fix : 프로필 관련 기능 수정
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/domain/ProfileImage.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/domain/repository/ProfileImageRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/exception/ProfileImageNotFoundException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/presentation/AssetController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/presentation/dto/response/ProfileImageDto.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/service/AssetService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/asset/service/AssetUtils.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/dto/request/RegisterRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/CredentialService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/image/service/ImageService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/User.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/service/UserService.java
Labels: fix, backend

#106 fix : 연급 복권 시간 관련 기능 수정
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/domain/WinningPensionLottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/domain/repository/WinningPensionLotteryJdbcRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/domain/vo/WinningPensionLotteryBaseInfoVo.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/dto/request/LotteryDrawDayDto.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/dto/request/WinningPensionLotteryCrawlingDto.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/dto/response/WinningPensionLotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/service/WinningPensionLotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/PensionLottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/domain/vo/PensionLotteryBaseInfoVo.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/dto/response/PensionLotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/service/PensionLotteryService.java
Labels: fix, backend

#108 feat : correctNumbers Boolean 타입으로 변경
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/domain/repository/LotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/LotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/response/LotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
Labels: fix, backend

#110 fix: get lottery 로직 변경
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/LotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/response/LotteryNumbersResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/response/LotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/response/OneRoundResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/presentation/dto/response/WinningLotteryNumbersResponse.java
Labels: fix, backend

#111 feat : 알림 관련 로직 작성
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/domain/DeviceToken.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/domain/NotificationMessage.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/domain/repository/DeviceTokenRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/exception/FcmTokenInvalidException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/presentation/NotificationController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/presentation/dto/request/RegisterDeviceTokenRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/service/FCMService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/service/NotificationService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/service/NotificationUtils.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/service/NotificationUtilsImpl.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/User.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/presentation/UserController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/presentation/dto/request/ChangeNotificationStatusRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/service/UserService.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/FCMConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/java/uttugseuja/lucklotteryserver/global/exception/InvalidFirebaseKeyException.java
  src/main/java/uttugseuja/lucklotteryserver/global/scheduler/NotificationScheduler.java
  src/main/resources/application.yml
Labels: feat, backend

#113 feat : 숫자 중복 예외 처리
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/exception/DuplicateNumberException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
Labels: feat, backend

#116 feat : dangling images 삭제 명령어 추가
  .github/workflows/cd.yml
Labels: feat, backend

#121 fix : spring 버전 업데이트로 인한 코드 대체
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/presentation/WinningLotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/GlobalExceptionHandler.java
  src/main/java/uttugseuja/lucklotteryserver/global/time/TimeTrace.java
  src/main/java/uttugseuja/lucklotteryserver/global/time/TimeTraceAspect.java
Labels: fix, backend

#123 feat : 사용자 알림 상태 api 제작
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/User.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/vo/UserInfoVO.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/presentation/UserController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/presentation/dto/response/UserNotificationStateResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/service/UserService.java
Labels: feat, backend
