Repository Uttug-Seuja/luck-lottery-server, pull requests merged in 2024-01, with the labels that each got.

#3 docs : DB 연결 및 초기 세팅
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: docs, backend

#5 feat : user entity 생성
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/AccountRole.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/User.java
Labels: feat, backend

#6 feat : Lottery Entity 생성
  src/main/java/uttugseuja/lucklotteryserver/LucklotteryserverApplication.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/domain/Lottery.java
  src/main/java/uttugseuja/lucklotteryserver/global/common/Rank.java
  src/main/java/uttugseuja/lucklotteryserver/global/database/BaseEntity.java
Labels: feat, backend

#10 feat : OIDC 소셜 로그인 인증
  build.gradle
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/OIDCDecodePayload.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/OauthFactory.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/OauthProvider.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/OauthStrategy.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/ConfigurationPropertiesConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/property/OauthProperties.java
  src/main/resources/application.yml
Labels: feat, backend

#13 feat : global exception 핸들러 생성
  src/main/java/uttugseuja/lucklotteryserver/global/error/ErrorResponse.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/GlobalExceptionHandler.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/LuckLotteryException.java
Labels: feat, backend

#14 feat : get openkey
  build.gradle
  src/main/java/uttugseuja/lucklotteryserver/global/api/FeignConfiguration.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/client/GoogleAuthClient.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/client/KakaoOauthClient.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/dto/OIDCKeyDto.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/dto/OIDCKeysResponse.java
  src/main/resources/application.yml
Labels: feat, backend

#16 feat : id token 유효성 검증
  build.gradle
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/GoogleOauthStrategy.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/KaKaoOauthStrategy.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/OauthOIDCProvider.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/java/uttugseuja/lucklotteryserver/global/exception/ExpiredTokenException.java
  src/main/java/uttugseuja/lucklotteryserver/global/exception/InvalidTokenException.java
  src/main/java/uttugseuja/lucklotteryserver/global/security/JwtOIDCProvider.java
Labels: feat, backend

#18 feat : SuccessResponse 생성
  src/main/java/uttugseuja/lucklotteryserver/global/successresponse/SuccessResponse.java
  src/main/java/uttugseuja/lucklotteryserver/global/successresponse/SuccessResponseAdvice.java
Labels: feat, backend

#19 feat : winning lottery open api 호출
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/winningLottery/domain/WinningLottery.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/client/WinningLotteryClient.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/dto/WinningLotteryDto.java
Labels: feat, fix, backend

#25 feat : ObjectMapper 예외 처리
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/exception/BadRoundException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/dto/WinningLotteryDto.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
Labels: feat, fix, backend

#26 feat : 시큐리티 적용
  build.gradle
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/repository/UserRepository.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/SecurityConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/java/uttugseuja/lucklotteryserver/global/exception/UserNotFoundException.java
  src/main/java/uttugseuja/lucklotteryserver/global/security/JwtTokenFilter.java
  src/main/java/uttugseuja/lucklotteryserver/global/security/JwtTokenProvider.java
  src/main/java/uttugseuja/lucklotteryserver/global/security/auth/AuthDetails.java
  src/main/java/uttugseuja/lucklotteryserver/global/security/auth/AuthDetailsService.java
  src/main/java/uttugseuja/lucklotteryserver/global/security/filter/CustomAuthenticationEntryPoint.java
Labels: feat, backend

#27 feat : random lottery 생성 및 저장
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/domain/Lottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/domain/repository/LotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/domain/vo/LotteryBaseInfoVo.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/LotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/response/LotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
Labels: feat, backend

#30 feat : 로또 등수 생성하기
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
  src/main/java/uttugseuja/lucklotteryserver/global/common/Rank.java
Labels: feat, backend

#32 fix : 난수 생성 api와 Lottery 저장 api 분리
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/LotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/response/RandomLotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
Labels: fix, backend

#33 Feat/lottery create
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/LotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/request/CreateLotteryRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
Labels: feat, backend

#36 feat : FeignClient 및 refreshToken redis 적용
  build.gradle
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/domain/RefreshTokenRedisEntity.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/domain/repository/RefreshTokenRedisEntityRepository.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/client/GoogleAuthClient.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/client/KakaoOauthClient.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/RedisConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/SecurityConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ExceptionFilter.java
  src/main/java/uttugseuja/lucklotteryserver/global/security/filter/CustomAuthenticationEntryPoint.java
  src/main/resources/application.yml
Labels: feat, backend

#38 feat : securityContext에서 유저 정보 가져오기 및 유저 정보 util로 분할
  src/main/java/uttugseuja/lucklotteryserver/global/utils/security/SecurityUtils.java
  src/main/java/uttugseuja/lucklotteryserver/global/utils/user/UserUtils.java
  src/main/java/uttugseuja/lucklotteryserver/global/utils/user/UserUtilsImpl.java
Labels: feat, backend

#41 feat : 로그인 기능 구현
  build.gradle
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/exception/RefreshTokenExpiredException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/CredentialController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/dto/request/RegisterRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/dto/request/TokenRefreshRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/dto/response/AccessTokenDto.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/dto/response/AuthTokensResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/dto/response/CheckRegisteredResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/CredentialService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/User.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/repository/UserRepository.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/RedisCacheConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/RedisConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/SecurityConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/java/uttugseuja/lucklotteryserver/global/security/JwtTokenProvider.java
Labels: feat, backend

#42 feat : id_token을 웹 api로 가져오는 기능
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/CredentialController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/dto/request/OauthCodeRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/dto/response/AfterOauthResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/dto/response/OauthLoginLinkResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/CredentialService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/GoogleOauthStrategy.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/KaKaoOauthStrategy.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/OauthStrategy.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/client/KakaoOauthClient.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/dto/OauthIdTokenResponse.java
  src/main/resources/application.yml
Labels: feat, backend

#44 fix : Lottery 저장할 때 user 추가
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/domain/Lottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
Labels: fix, backend

#46 fix : 등수 계산하기 함수 기능 분리하기
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
Labels: fix, backend

#47 feat : user와 관련된 로또 api 작성
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/domain/Lottery.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/domain/repository/LotteryRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/domain/vo/LotteryBaseInfoVo.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/LotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/response/LotteryNumbersResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/response/LotteryResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/presentation/dto/response/WinningLotteryNumbersResponse.java
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/service/LotteryService.java
Labels: feat, backend

#49 fix : 회원가입 로그인 테스트 api 시큐리티 설정 허용
  src/main/java/uttugseuja/lucklotteryserver/global/config/SecurityConfig.java
Labels: fix, backend

#53 docs : ci.yml 생성
  .github/workflows/ci.yml
Labels: fix, docs, backend
