Repository Uttug-Seuja/luck-lottery-server, pull requests merged in 2024-03, with the labels that each got.

#125 feat : 구글 소셜로그인 id_token 서버에서 받아오는 기능 구현
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/exception/NoSuchPublicKeyException.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/CredentialController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/GoogleOauthStrategy.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/OauthOIDCProvider.java
  src/main/java/uttugseuja/lucklotteryserver/global/api/client/GoogleAuthClient.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/java/uttugseuja/lucklotteryserver/global/exception/RSAAlgorithmException.java
  src/main/java/uttugseuja/lucklotteryserver/global/security/JwtOIDCProvider.java
  src/main/resources/application.yml
Labels: feat, backend

#127 feat : logout 시 deviceToken 삭제
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/event/LogoutUserEvent.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/CredentialService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/domain/repository/DeviceTokenRepository.java
  src/main/java/uttugseuja/lucklotteryserver/domain/notification/event/DeviceTokenEvent.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/User.java
  src/main/java/uttugseuja/lucklotteryserver/global/event/DeviceTokenServiceEventHandler.java
  src/main/java/uttugseuja/lucklotteryserver/global/event/DomainEvent.java
  src/main/java/uttugseuja/lucklotteryserver/global/event/EventPublisherAspect.java
  src/main/java/uttugseuja/lucklotteryserver/global/event/Events.java
Labels: feat, backend

#130 Fix : 유저 닉네임 변경과 프로필 이미지 변경 한번에 처리하도록 기능 수정
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/presentation/CredentialController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/presentation/UserController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/presentation/dto/request/ChangeUserInfoRequest.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/service/UserService.java
Labels: fix, backend

#132 feat : 회원 탈퇴 시 DeviceToken 삭제 Event 발행하기
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/event/LogoutUserEvent.java
  src/main/java/uttugseuja/lucklotteryserver/domain/credential/service/CredentialService.java
  src/main/java/uttugseuja/lucklotteryserver/domain/user/domain/User.java
  src/main/java/uttugseuja/lucklotteryserver/global/event/EventPublisherAspect.java
Labels: feat, fix, backend

#135 fix : 에러 코드 변경 및 BaseEntity 적용
  src/main/java/uttugseuja/lucklotteryserver/domain/lottery/domain/Lottery.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ExceptionFilter.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/GlobalExceptionHandler.java
Labels: fix, backend

#136 feat : Valid 예외 처리 추가
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/presentation/WinningPensionLotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/PensionLotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/domain/pensionlottery/presentation/dto/request/CreatePensionLotteryRequest.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/SecurityConfig.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/ErrorCode.java
  src/main/java/uttugseuja/lucklotteryserver/global/error/exception/GlobalExceptionHandler.java
Labels: feat, fix, backend

#138 fix : Admin만 당첨 로또 저장 api 접근
  src/main/java/uttugseuja/lucklotteryserver/domain/winning_lottery/presentation/WinningLotteryController.java
  src/main/java/uttugseuja/lucklotteryserver/global/config/SecurityConfig.java
Labels: fix, backend

#142 refactor :crawling method separation
  src/main/java/uttugseuja/lucklotteryserver/domain/WinningPensionlottery/service/WinningPensionLotteryService.java
Labels: refactor, backend

#144 feat: aws 서버 시간 서울로 설정
  src/main/java/uttugseuja/lucklotteryserver/LucklotteryserverApplication.java
Labels: feat, backend
